"""Add graph_path to UploadedData

Revision ID: 028fada59365
Revises: 
Create Date: 2025-04-22 18:32:41.030851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '028fada59365'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uploaded_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=120), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('graph_path', sa.String(length=200), nullable=True),
    sa.Column('upload_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('uploaded_data')
    # ### end Alembic commands ###
